name: Deploy to AWS
on:
  push:
    branches:
      - main

jobs:
  cancel_previous_runs:
    name: Cancel previous runs
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

  deploy_aws:
    name: Deploy AWS
    runs-on: ubuntu-latest
    needs:
      - cancel_previous_runs
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: install dependencies
        run: 'npm ci'

      - name: compile typescript
        run: 'npm run build'

      - name: Start deployment
        uses: bobheadxi/deployments@master
        id: deployment
        with:
          step: start
          token: ${{ github.token }}
          env: production

##      - name: Deploy Stack
 #       uses: docker://kikemnzz/automate-cdk-github-action-kmzz:v1.0.0
 #       env:
 #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
 #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 #         AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
 #       with:
 #         #cdk_version: '1.9.0'
 #         cdk_action: 'deploy --verbose --require-approval never'

      - name: Update deployment status
        uses: bobheadxi/deployments@master
        # Runs even if previous jobs failed or were cancelled
        if: always()
        with:
          step: finish
          token: ${{ github.token }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: "https://app.ferdig.de"
